resources:
  - git@github.com:poly-glot/personal-cloud/deployment/base/?ref=main

namePrefix: local-

configMapGenerator:
  - name: database-map
    env: config.properties
    behavior: replace

patches:
  - path: deployment.yaml
