apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
        - name: webappcontainer
          image: "shehryar:latest"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: database-map
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tool: db
    spec:
      containers:
        - name: phpmyadmin
          image: "phpmyadmin:latest"
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mysql-service.database.svc.cluster.local"

