apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/poly-glot/personal-cloud//deployment/base/?ref=main

namePrefix: main-

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: database-map

images:
- name: webapp:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/shehryar-personal-site
  newTag: e9c0421d263f2d08020572d1d0fa60174a0e08f1
