apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: main-

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: database-map

images:
- name: shehryar:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/shehryar-personal-site
  newTag: e11c6e36af5e467f203b3cba07d7050ad8c1668c
