apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: main-

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: database-map

images:
- name: shehryar:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/shehryar-personal-site
  newTag: 185ccca2aad97e664d417269a9cc46a0d4fd8eb7
