apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git@github.com:poly-glot/personal-cloud/deployment/base/?ref=main

namePrefix: main-

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: database-map

images:
- name: shehryar:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/shehryar-personal-site
  newTag: 2335a864b371b034e7481c39da46ca42cd6d5fa2
