name: "Build"

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build & Push Docker Image
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: shehryar-personal-site
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Tag and push a container image
        id: tag-and-push-image
        run: |
          docker build -t shehryar-personal-site .
          docker tag "shehryar-personal-site" "${{ steps.get-ocir-repository.outputs.repo_path }}:main"
          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:main"
