name: "Build"

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build & Push Docker Image
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: shehryar-personal-site
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Set GITHUB_REF_NAME
        id: set-ref-name
        run: echo "GITHUB_REF_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ steps.get-ocir-repository.outputs.repo_path }}:${{ github.sha }}"

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OCI_OKE_CLUSTER_OCID }}

      - name: Deploy
        run: |
          cd deployment/overlays/${{ env.GITHUB_REF_NAME }}  
          
          kustomize edit set image shehryar:latest=${{ steps.get-ocir-repository.outputs.repo_path }}:${{ github.sha }}
          
          git config --global user.name "@poly-glot-bot"
          git config --global user.email "poly-glot-bot@users.noreply.github.com"          
          git commit -am "feat: Update deployment image tag to ${{ github.sha }} [skip ci]"
          git push          
          
          kubectl apply -k .   
