name: "Build webserver"

on:
  push:
    branches:
      - main
    paths:
      - webserver/**
env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Build & Push Docker Image
    outputs:
      REPO_PATH: ${{ steps.get-ocir-repository.outputs.repo_path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: shehryar-webserver
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./webserver
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ steps.get-ocir-repository.outputs.repo_path }}:main"
